#!/usr/bin/env python3
import argparse
import webbrowser
from collections import namedtuple
from datetime import datetime

import requests

NOW = datetime.now()
URL = f'https://nolaborables.com.ar/api/v2/feriados/{NOW.year}'
MESES = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
MAP_MESES = {i: mes for i, mes in zip(range(1, 13), MESES)}


def iter_feriados(json_data):
    Feriado = namedtuple('Feriado', 'dt info')

    for each_data in json_data:
        feriado_dt = datetime(NOW.year, each_data['mes'], each_data['dia'])
        feriado_obj = Feriado(dt=feriado_dt, info=each_data['info'])
        yield feriado_obj


def next_feriado(json_data):
    for feriado in iter_feriados(json_data):
        if feriado.dt <= NOW:
            continue
        return feriado


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-c',
        '--color',
        type=str,
        default='ffab04',
        help='Text color (default=%(default)s)'
    )
    parser.add_argument(
        '-l',
        '--label',
        type=str,
        default='Feriado',
        help='Label text (default=%(default)s)'
    )
    parser.add_argument(
        '-i',
        '--info',
        action='store_true',
        help='Show info about feriado'
    )
    args = parser.parse_args()

    color = f'#{args.color}'
    try:
        request = requests.get(URL)
    except Exception:
        text = f'%{{F{"#f00"}}} Connection error'
    else:
        json_data = request.json()
        feriado_obj = next_feriado(json_data)

        if args.info:
            webbrowser.open_new_tab(feriado_obj.info)
            return
        month = MAP_MESES[feriado_obj.dt.month]

        text = f'{args.label}: %{{F{color}}} {feriado_obj.dt.day} {month}'

        print(text)


if __name__ == '__main__':
    main()
